version: '2.0'

services:
  server:
    image: 'backend:latest'
    ports:
      - "8080:8080"
    build:
      context: ./server
    container_name: server
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  
  client:
    image: frontend:latest
    ports:
      - "80:3000"
    build:
      context: ./client
    container_name: client
    depends_on:
      - server
      - db
    stdin_open: true
    tty: true
  
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "8082:5432"
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
